### ISSUE TITLE
Fails to build on boot2docker 1.6.2

### ISSUE THREAD

**Issue by pgleghorn** [biemond/docker-weblogic-puppet#1]
Fails to build on boot2docker 1.6.2

...
Step 17 : COPY jdk-7u55-linux-x64.tar.gz /software/
 ---> 05343bd084f3
Removing intermediate container 99184f4a2d9d
Step 18 : COPY fmw_12.1.3.0.0_wls.jar /var/tmp/install/
 ---> d76f5f822757
Removing intermediate container b3c7ad9e14c0
Step 19 : RUN puppet apply /etc/puppet/site.pp --verbose --detailed-exitcodes ||
 [ $? -eq 2 ]
 ---> Running in 0d784bca3d22
Warning: Facter: Already evaluated rest at /usr/local/share/gems/gems/facter-2.4
.4/lib/facter/gce.rb:4, reevaluating anyways
Warning: Facter: Already evaluated rest at /usr/local/share/gems/gems/facter-2.4
.4/lib/facter/ec2.rb:21, reevaluating anyways
Warning: Facter: Already evaluated rest at /usr/local/share/gems/gems/facter-2.4
.4/lib/facter/ec2.rb:38, reevaluating anyways
Error: Evaluation Error: Error while evaluating a Function Call, Could not find
class ::jdk7 for 3f3c2314a6b0.home at /etc/puppet/site.pp:60:3 on node 3f3c2314a
6b0.home
INFO[0105] The command [/bin/sh -c puppet apply /etc/puppet/site.pp --verbose --
detailed-exitcodes || [ $? -eq 2 ]] returned a non-zero code: 1

**Comment by biemond** [comment]
Hi,

I am now doing some test and let you know if I got the same issue.

cheers

**Comment by biemond** [comment]
Solved it,

first I didn't install the git package for librarian-puppet, so that failed.
added some extra output to librarian-puppet

I installed with yum puppet 3.8.1  but updated it with gem to 4.1.0,  that gave some strange errors.
and also added module path and hiera config to the puppet command.

thanks

**Comment by pgleghorn** [comment]
many thanks!
